N_CONNECTION_PER_PEER = 10
MAX_QUEUE_SIZE = 20
QUEUES_PER_PEER = 2
ALLOCATED_PORT_RANGE = 10
PORT_RANGE = range(10000, 10100)
MARKETPLACE_QUANTITY = (PORT_RANGE.stop - PORT_RANGE.start) / N_CONNECTION_PER_PEER
WAIT_CONNECTION_TIME = 1
DEFAULT_HOST = "localhost"